services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    environment:
      - NGINX_PORT=80
    depends_on:
      - oauth2-proxy

  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.9.0
    ports:
      - "4180:4180"
    environment:
      - OAUTH2_PROXY_UPSTREAMS=http://nginx:80
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost:4180/oauth2/callback
      - OAUTH2_PROXY_PROVIDER=entra-id
      - OAUTH2_PROXY_OIDC_ISSUER_URL=https://login.microsoftonline.com/${TENANT_ID}/v2.0
      - OAUTH2_PROXY_CLIENT_ID=${CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${CLIENT_SECRET}
      - OAUTH2_PROXY_SCOPE=openid email
      - OAUTH2_PROXY_COOKIE_SECRET=${COOKIE_SECRET}
      - OAUTH2_PROXY_EMAIL_DOMAINS=${VALID_DOMAIN}
